### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by rohitgoyal** [zmxv/react-native-sound#203]
Sounds are working on iOS using the below code but not working on Android. I have notification.wav file in the android/app/src/main/res/raw directory.  Help please.

```
const s = new Sound('notification.wav', (e) => {
      if (e) {
        console.log('error', e);
        return;
      }

      s.play(() => s.release());
    });
```

**Comment by Winglonelion** [comment]
change  your react-native-sound package dependency by `"react-native-sound": "git+https://github.com/zmxv/react-native-sound.git#fix_android_network_sound"` 

try `npm install` again.

**Comment by rohitgoyal** [comment]
@Winglonelion 
Installed the react-native-sound with your PR. Below is the code to play the sound. On iOS it plays the sound. On Android there are no errors and it prints the log "sound played" but there is no sound. 

```
playTapSound(){
    const s = new Sound('../sounds/tap.wav', (e) => {
      if (e) {
        console.log('error', e);
        return;
      } else{
        console.log('sound loaded successfully: '+s.isLoaded()+" volume is "+s.getVolume())
        s.play((success) => {
          if(success){
            console.log('sound played')
            s.release();
          } else{
            console.log('sound failed to play')
          }
        });
      }
    });
  }
```

**Comment by benvium** [comment]
Can you try this on new version 0.10.2? This should be fixed

**Comment by rohitgoyal** [comment]
@benvium It worked just the first time but after that i doesn't work ever. After closing the app and reopening, the sound does not work even for the first time too. All the time I am getting the sound played callback though.

**Comment by benvium** [comment]
@rohitgoyal Can you have a go with `react-native-sound-demo` and see if that works for you?

**Comment by rohitgoyal** [comment]
Tried it. No sounds in react-native-sound-demo on android too. :-/

**Comment by benvium** [comment]
Which device and OS are you on?

**Comment by rohitgoyal** [comment]
Google Nexus 6P 
OS: 6.0.0
API 23

**Comment by s5963028** [comment]
I have the same problem.
"duration in seconds: 3.63number of channels: -1"
but when i try to play it i receive this error from callback:
"playback failed due to audio decoding errors"

**Comment by alexprice91** [comment]
bump

**Comment by ShinichiroMike** [comment]
> I have the same problem.
"duration in seconds: 3.63number of channels: -1"
but when i try to play it i receive this error from callback:
"playback failed due to audio decoding errors"

The same here. Running on android device.

**Comment by basvasilich** [comment]
> "duration in seconds: 3.63number of channels: -1"
> but when i try to play it i receive this error from callback:
> "playback failed due to audio decoding errors"

The same here.
Samsung Galaxy S6
OS: 5.1.0
API 22

**Comment by DavitVosk** [comment]
Anybody has solved the problem?

**Comment by DavitVosk** [comment]
solved... just put "music.play()" out of constructor error part, like this: 

const music = new Sound('nargiz_vdvoyom.mp3', Sound.MAIN_BUNDLE, (error) => {
			if (error) {
				console.log('failed to load the sound', error);
				return;
			}
			// loaded successfully
			console.log('duration in seconds: ' + music.getDuration() + ' number of channels: ' + music.getNumberOfChannels());

		// Play the sound with an onEnd callback
			music.play((success) => {
				if (success) {
					console.log('successfully finished playing');
				} else {
					console.log('playback failed due to audio decoding errors');
				}
			});
		});

**Comment by pehlert** [comment]
What @DavitVosk means is to put the play() call **inside the constructor callback**. This has solved playback for me.

**Comment by gvenk** [comment]
`new Sound()` uses [android.media.MediaPlayer.prepareAsync()](https://developer.android.com/reference/android/media/MediaPlayer.html#prepareAsync()). So `new Sound()` returns immediately and it could have been not prepared completely. You could try to add a timeout, but it's most save to start playing from the `onError` callback, I think. (and the name onError is a bit confusing)

**Comment by gvenk** [comment]
And the original title of this issue is: 
> Not working on Android | number of channels is -1

But that is not the real issue, because it will always return -1 on Android because `getNumberOfChannels()` hasn't been implemented on Android. See also:  #258

**Comment by gvenk** [comment]
@rohitgoyal Is your problem fixed with the latest version? I see that you already were playing from the onError callback

**Comment by rohitgoyal** [comment]
@gvenk I got it working while playing from the Main Bundle but it still doesn't work from a dir path. 
In case of Main bundle it doesn't work with an Emulator. 
Lot of people might be testing it on an Emulator.

**Comment by gvenk** [comment]
@rohitgoyal if you want to get it working from a dir path in the app, you have to remove the second parameter `Sound.MAIN_BUNDLE`. The onError handler must be the second parameter.

Annoying it's not working on the emulator. I don't have any problem with the emulator, so it's difficult to debug :-(

**Comment by rohitgoyal** [comment]
@gvenk I did try it after removing the second parameter only. It didn't work on Android but worked on iOS(Check 3rd reply on the thread).
 
On Emulator it might be specific emulator issue as well. I tried on genymotion emulator with following config
Google Nexus 6P
OS: 6.0.0
API 23

**Comment by gvenk** [comment]
@rohitgoyal ah, I overlooked that comment. Was this on a real device, or emulator? 

Ah, I don't have access to the genymotion emulator, so I'm not able to debug this, sorry.

**Comment by rohitgoyal** [comment]
@gvenk On a real device. 
No issues. As of now things are working for me using Main Bundle :)

**Comment by gvenk** [comment]
Ok, @rohitgoyal so this issue can be closed according to you? 

Maybe we have to add a note about which emulators we know are working with this project.

**Comment by rohitgoyal** [comment]
@gvenk Yeah I guess. You can add the note for sound not playing on emulator and sound not playing on real android device using dir path.

**Comment by trepidity** [comment]
@gvenk does this relate to switching from `true` / `false`?

**Comment by gvenk** [comment]
@trepidity don't think so

**Comment by Faisal-Manzer** [comment]
```
// audio is a remote url
s = new Sound(audio, null, (e) => {
        if (e) {
            console.log('error', e);
        } else {
            console.log('sound loaded successfully: ' + s.isLoaded() + " volume is " + s.getVolume());

            s.play((success) => {
                if (success) {
                    console.log('sound played');
                    s.release();
                } else {
                    console.log('sound failed to play')
                }
            });
        }
    });
```
this solved my issue, `Sound.MAIN_BUNDLE` and `play()` took place inside the callback function

React = 16.5.2
React-Native = 0.57.1
React-Native-Sound = 0.10.9

**Comment by afilp** [comment]
@Faisal-Manzer But does this mean that we have to initiate the same sound as `new`, every time we use it? I used to put the sound in a window variable (e.g. `window.sound1 = new Sound(...)`, so that I could just `play` it later in a different route. It used to work, now not. What is the change needed? Thanks!

**Comment by gurol** [comment]
Android could not play the sound embedded in the bundle. There is no problem in iOS (even you can initiate the sound once and then use play() function consecutively.

**Comment by kyle-belle** [comment]
Im still experiencing this issue on android still. (June 7th, 2021)

Device: OnePlus 7Pro - Android 10

I am trying to play from network
the number of channels is always -1;

```js
let s;
// component
() => {
const onPressPlay = () => {
        
        if(playing){
            s.pause();
            setPlaying(false);
        }else{
            if(!songLoaded){
                setSongLoading(true)
                s = new Sound(audio_src, null, (error) => {
                    if(error){
                        console.log(e);
                        Alert.alert("Audio Error", error);
                        setSongLoading(false);
                        return;
                    }

                    console.log("Success Loading Audio");
                    console.log('duration in seconds: ' + s.getDuration() + 'number of channels: ' + s.getNumberOfChannels());

                    setSongLoading(false);
                    setSongLoaded(true);
                    s.play((success) => {
                        if(success){
                            console.log("Success Playing Audio");
                            setPlaying(true)
                        }else{
                            console.log("Error Playing Audio");
                        }
                    })
                });
                setSongLoaded(true);
            }else{
                s.play((success) => {
                    if(success){
                        console.log("Success Playing Audio");
                        setPlaying(true)
                    }else{
                        console.log("Error Playing Audio");
                    }
                });
            }
        }
    }
}
```
