### ISSUE TITLE
new Sound(...) can't callback

### ISSUE THREAD

**Issue by MackYang** [zmxv/react-native-sound#345]
```
  var sound = new Sound("../../assets/so1und/msg.mp3", "", (error,opt) => {
      console.log("error");// **can't output in console...**
      console.log(error);
      console.log("opt");
      console.log(opt);
      if (error) {
        console.log("failed to load the sound", error);
      }
    });
```

**Comment by schumannd** [comment]
I am experiencing the same issue but only on android. Have you solved your problem?

**Comment by paulmelnikow** [comment]
I believe this was fixed in #405!

**Comment by cbahir** [comment]
@paulmelnikow 
- Sorry to say but issue is still occurs
here is my code,
`play = async () => {
    if (this.sound) {
      this.sound.play(this.playComplete);
      this.setState({ playState: 'playing' });
    } else {
      const filepath = require('./songs/sound3.mp3');
      console.log('[Play] :', filepath);

      this.sound = new Sound(filepath, "", error => {
        console.log('Callback');
        if (error) {
          console.log('failed to load the sound', error);
          Alert.alert('Notice', 'audio file error. (Error code : 1)');
          this.setState({ playState: 'paused' });
        } else {
          this.setState({ playState: 'playing', duration: this.sound.getDuration() });
          this.sound.play(this.playComplete);
          console.log('Duration :', this.state.duration);
        }
      });
    }
  }`

i want - if error not occur then else part will be execute.
